[package]
name = "storm-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
storm-utils = { version = "=0.1", path = "../storm-utils", default-features = false }
